name: Zooniverse
dependencies:
  - python==3.7
  - geopandas
  - rasterio
  - shapely
  - pandas
  - pytest
  - pip:
    - panoptes-aggregation
    - panoptes
    - DeepForest
    - comet_ml
    - paramiko



