name: EvergladesTools
channels: 
  - defaults
  - conda-forge
dependencies:
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit
  - dask
  - distributed
  - bioconda::snakemake
  - pip:
    - deepforest
    - pandas
    - geopandas
    - dask_jobqueue
    - panoptescli
    - comet_ml
    - paramiko
    - panoptes_client
    - slidingwindow
    - xmltodict
    - Panoptes
    - PyYAML==6.0
    - shapely
    - pytest
    - rasterio
    - yapf
    - black
    - pytest-cov
    - pytest-xdist
    - pdoc
    - rio-mbtiles
    - boto3
