name: Zooniverse
channels:
  - conda-forge
dependencies:
  - rasterio
  - shapely
  - pandas
  - pytest
  - pip:
    - panoptes-aggregation
    - panoptes
    - DeepForest
    - comet_ml
    - paramiko



