name: EvergladesTools
channels: 
  - defaults
dependencies:
  - conda-forge::python>=3.9
  - bioconda::snakemake
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit=11.3
  - pip
  - dask
  - distributed
  - pip:
    - DeepForest
    - pytest
    - comet_ml
    - dask_jobqueue
    - rio-mbtiles
    - mapboxcli
    - panoptes_client
