name: Zooniverse
channels: 
  - defaults
dependencies:
  - python==3.7
  - geopandas
  - rasterio
  - shapely
  - pandas
  - pytest
  - pip:
    - panoptescli
    - DeepForest
    - comet_ml
    - paramiko



