name: Zooniverse
channels: 
  - conda-forge
dependencies:
  - geopandas
  - shapely
  - pandas
  - pytest
  - pip
  - dask
  - distributed
  - pip:
    - DeepForest
    - panoptescli
    - mapboxcli
    - rasterio
    - deepforest
    - comet_ml
    - paramiko
    - opencv-python



