name: Zooniverse
channels: 
  - conda-forge
dependencies:
  - python==3.7
  - geopandas
  - shapely
  - pandas
  - pytest
  - pip
  - pip:
    - panoptescli
    - DeepForest
    - comet_ml
    - paramiko


